### ISSUE TITLE
Update READMe Doc

### ISSUE THREAD

**Issue by blong1996** [ymittal/codeu_project_2017#33]
- replace original readme instructions with details on our version of the chat application

**Comment by blong1996** [comment]
- replace original readme instructions with details on our version of the chat application

**Comment by ymittal** [comment]
@blong1996 Would you be able to include instructions on how to setup a Firebase app and get the needed `google-services.json` file?

**Comment by blong1996** [comment]
@ymittal I actually am not quite sure how the `google-services.json` file was created. and as far as the how to for Firebase, isn't it safe to providd the resources in the design doc for this? (i.e. links to Firebase documentation)

**Comment by ymittal** [comment]
Refer to #39
